"""add_gamification_training_tables

Revision ID: 34bae2adbb18
Revises: 69565a8ff510
Create Date: 2026-01-31 22:33:04.130534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bae2adbb18'
down_revision: Union[str, None] = '69565a8ff510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('races',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('5k', '10k', 'half_marathon', 'marathon', 'ultra_50k', 'ultra_100k', 'trail', 'other', name='race_category_enum'), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('elevation_gain_m', sa.Integer(), nullable=True),
    sa.Column('cutoff_time', sa.String(length=50), nullable=True),
    sa.Column('mountain_level', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('race_type', sa.String(length=50), nullable=True),
    sa.Column('target_time', sa.String(length=50), nullable=True),
    sa.Column('actual_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('upcoming', 'completed', 'dns', 'dnf', name='race_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_logs', sa.Integer(), nullable=False),
    sa.Column('total_photos', sa.Integer(), nullable=False),
    sa.Column('perfect_weeks', sa.Integer(), nullable=False),
    sa.Column('days_on_target', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('nutrition_score', sa.SmallInteger(), nullable=False),
    sa.Column('training_score', sa.SmallInteger(), nullable=False),
    sa.Column('overall_score', sa.SmallInteger(), nullable=False),
    sa.Column('nutrition_feedback', sa.Text(), nullable=True),
    sa.Column('training_feedback', sa.Text(), nullable=True),
    sa.Column('ai_suggestions', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('race_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('weeks', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai_generated', name='plan_source_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='day_enum'), nullable=False),
    sa.Column('time_of_day', sa.Enum('morning', 'evening', name='time_enum'), nullable=False),
    sa.Column('session_type', sa.Enum('easy_run', 'tempo', 'interval', 'long_run', 'recovery', 'rest', 'strength', 'cross_training', 'race', 'trail', name='session_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_distance_km', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('actual_distance_km', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('target_duration_min', sa.Integer(), nullable=True),
    sa.Column('actual_duration_min', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_sessions')
    op.drop_table('training_plans')
    op.drop_table('weekly_feedback')
    op.drop_table('user_stats')
    op.drop_table('user_badges')
    op.drop_table('races')
    op.drop_table('badges')
    # ### end Alembic commands ###
