"""initial migration

Revision ID: 69565a8ff510
Revises: 
Create Date: 2026-01-31 22:02:08.986320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69565a8ff510'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('calorie_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('target_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('consumed_kcal', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('status', sa.Enum('normal', 'near_limit', 'over', 'under', name='log_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calorie_log_user_date', 'calorie_logs', ['user_id', 'log_date'], unique=True)
    op.create_table('progress_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('period_type', sa.Enum('daily', 'weekly', 'monthly', name='period_type_enum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_intake_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('avg_target_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_intake_kcal', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('days_on_target', sa.SmallInteger(), nullable=False),
    sa.Column('days_logged', sa.SmallInteger(), nullable=False),
    sa.Column('consistency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_streak', sa.SmallInteger(), nullable=False),
    sa.Column('longest_streak', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_user_period', 'progress_summaries', ['user_id', 'period_type', 'period_start'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('running_frequency', sa.Enum('1-2', '3-4', '5-6', '7+', name='frequency_enum'), nullable=False),
    sa.Column('training_intensity', sa.Enum('easy', 'moderate', 'hard', 'very_hard', name='intensity_enum'), nullable=False),
    sa.Column('goal', sa.Enum('deficit', 'performance', 'bulking', name='goal_enum'), nullable=False),
    sa.Column('bmr', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('tdee', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('daily_target_kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('food_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calorie_log_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('ai_photo', 'manual', 'search', 'favorite', name='source_enum'), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('portion_desc', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_raw_response', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calorie_log_id'], ['calorie_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_entries_favorite', 'food_entries', ['user_id', 'is_favorite'], unique=False)
    op.create_index('idx_food_entries_log', 'food_entries', ['calorie_log_id'], unique=False)
    op.create_index('idx_food_entries_user', 'food_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_food_entries_user', table_name='food_entries')
    op.drop_index('idx_food_entries_log', table_name='food_entries')
    op.drop_index('idx_food_entries_favorite', table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_table('user_profiles')
    op.drop_index('idx_refresh_token_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_progress_user_period', table_name='progress_summaries')
    op.drop_table('progress_summaries')
    op.drop_index('idx_calorie_log_user_date', table_name='calorie_logs')
    op.drop_table('calorie_logs')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
